# Generated by Django 5.2.6 on 2026-01-13 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='', help_text='Hex color code for UI display (e.g., #FF5733)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Path in storage: {user_id}/folder/file.ext', upload_to='')),
                ('size_bytes', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type detected via python-magic', max_length=255)),
                ('checksum_sha256', models.CharField(db_index=True, help_text='SHA256 hash for integrity verification', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='files', to='files.tag')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tags_user_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='tags_user_name_unique'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'file'], name='files_user_file_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', '-uploaded_at'], name='files_user_recent_idx'),
        ),
    ]
