# Generated by Django 5.2.6 on 2026-01-21 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('user', 'file'), name='files_user_path_unique'),
        ),
    ]
