# Generated by Django 5.2.6 on 2026-01-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0002_add_unique_constraint_user_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quota', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('quota_bytes', models.BigIntegerField(default=10737418240, help_text='Storage quota limit in bytes')),
                ('used_bytes', models.BigIntegerField(default=0, help_text='Currently used storage in bytes')),
            ],
            options={
                'verbose_name': 'User Quota',
                'verbose_name_plural': 'User Quotas',
                'constraints': [models.CheckConstraint(condition=models.Q(('quota_bytes__gte', 0)), name='quota_bytes_non_negative'), models.CheckConstraint(condition=models.Q(('used_bytes__gte', 0)), name='used_bytes_non_negative')],
            },
        ),
    ]
