# Generated by Django 5.2.6 on 2026-01-24 14:05

from django.db import migrations
from django.db.models import Sum


def populate_quotas(apps, schema_editor):  # noqa: D103
    User = apps.get_model('auth', 'User')
    UserQuota = apps.get_model('files', 'UserQuota')
    File = apps.get_model('files', 'File')

    # Default quota: 10 GB in bytes
    default_quota = 10 * 1024 * 1024 * 1024

    for user in User.objects.all():
        # Calculate current usage from files
        total_usage = File.objects.filter(
            user=user,
        ).aggregate(
            total=Sum('size_bytes'),
        )['total'] or 0

        # Create quota record
        UserQuota.objects.get_or_create(
            user=user,
            defaults={
                'quota_bytes': default_quota,
                'used_bytes': total_usage,
            },
        )


def reverse_quotas(apps, schema_editor):  # noqa: D103
    UserQuota = apps.get_model('files', 'UserQuota')
    UserQuota.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0003_add_userquota'),
    ]

    operations = [
        migrations.RunPython(populate_quotas, reverse_quotas),
    ]
