# Generated by Django 5.2.6 on 2026-01-31 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_populate_existing_user_quotas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When file was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True if file is in trash'),
        ),
        migrations.AddField(
            model_name='file',
            name='original_path',
            field=models.CharField(blank=True, default='', help_text='Original storage path before deletion (for restore)', max_length=1024),
        ),
        migrations.AddField(
            model_name='file',
            name='trash_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique filename in trash (includes timestamp)', max_length=512),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'is_deleted', 'deleted_at'], name='files_user_trash_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'trash_name'], name='files_user_trash_name_idx'),
        ),
    ]
