# Generated by Django 5.2.6 on 2026-01-19 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDAVSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('user_agent', models.CharField(blank=True, default='', help_text='Client user agent string', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Session start time')),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True, help_text='Last activity timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webdav_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebDAV Session',
                'verbose_name_plural': 'WebDAV Sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='webdav_user_activity_idx')],
            },
        ),
    ]
